version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - checkout
      - run: javac TodoList.java
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@15.206.185.86 "cd /home/java && git pull origin main" 

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main